apiVersion: v1
kind: Service
metadata:
  name: sai-eks
  namespace: sai
spec:
  selector:
    app: sai-eks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
